### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by edrush** [jackd248/ampersand#1]
Hi,

the debug log says:

`12:26 $ cat electron-ampersand/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@1.3.21
3 info using node@v0.10.24
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart electron-ampersand@0.2.0
6 info start electron-ampersand@0.2.0
7 verbose unsafe-perm in lifecycle true
8 info electron-ampersand@0.2.0 Failed to exec start script
9 error electron-ampersand@0.2.0 start:`electron .`
9 error Exit status 126
10 error Failed at the electron-ampersand@0.2.0 start script.
10 error This is most likely a problem with the electron-ampersand package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     electron .
10 error You can get their info via:
10 error     npm owner ls electron-ampersand
10 error There is likely additional logging output above.
11 error System Linux 3.19.0-32-generic
12 error command "/usr/local/bin/node" "/usr/local/bin/npm" "start"
13 error cwd /media/woe/daten/daten/work/repos/electron-ampersand
14 error node -v v0.10.24
15 error npm -v 1.3.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]
`

Regards!

**Comment by konradmichalik** [comment]
Resolved with current version.
